### ISSUE TITLE
Assign torrent jumps to wrong section in elementum

### ISSUE THREAD

**Issue by VisionaiR3D** [elgatito/context.elementum#28] opened 2024-03-06 19:56 UTC
When you go to the context menu and select assign torrent kodi goes to elementum->torrent history. If you select a torrent from this list it wont work. Instead you have to go to elementum->torrents and select a file from there.

**Expected Behavior**
Assign torrent jumps to elementum->torrents

**Current Behavior**
Assign torrent jumps to elementum->torrent history

**Steps to Reproduce (for bugs)**
Play a torrent in elementum. > select a title from your database > open the elementum context menu > click assign torrent

**Possible Solution**
Make it jump to the correct section in elementum

edit plugin.py

edit line 74 and 76 to the following

file = xbmcgui.Dialog().browseSingle(1, ADDON.getLocalizedString(32010), 'files', '', False, False, 'plugin://plugin.video.elementum/torrents/')

if not file or file == 'plugin://plugin.video.elementum/torrents/':

**Comment by VisionaiR3D** [comment] 2024-03-06 20:06
edit plugin.py 

edit line 74 and 76 to the following to fix the problem.

  file = xbmcgui.Dialog().browseSingle(1, ADDON.getLocalizedString(32010), 'files', '', False, False, 'plugin://plugin.video.elementum/torrents/')

    if not file or file == 'plugin://plugin.video.elementum/torrents/':

**Comment by elgatito** [comment] 2024-03-07 11:21
@VisionaiR3D @antonsoroko 

There are number of issues highlighted.

https://github.com/elgatito/context.elementum/blob/master/plugin.py#L91-L105

There are different URLs generated by context plugin and get called to make an assignment. 
The idea is to assign torrent hash code (not the active torrent or history torrent, but a hash code of a torrent). 

https://github.com/elgatito/elementum/blob/master/api/torrents.go#L110

And initially it was designed to work with torrent history, so that you select any torrent from history and we assign that hash code to a media entity (movie/episode/show/season).

Something is not working, as I see that somehow torrent is not assigned, but is trying to be added to the session (which should not happen). We just need to get a hash from selected item and assign to a media entity.

**Comment by antonsoroko** [comment] 2024-03-07 12:07
@elgatito  i already have a fix for it. i just did not have a chance to push it.

**Comment by antonsoroko** [comment] 2024-03-07 12:36
so, as far as i remember, when i developed this feature i tested both locations: "torrents history" and "active torrents list", and i decided to use  "torrents history" as default since it usually has more torrents.

but now i realize that most likely i used a torrent that was in both "torrents history" and "active torrents list".
and the issue is that i used GetTorrentFromParam that uses GetTorrentByHash that does FindByHash for **Queue**, so if torrent is not in the queue - it can not find torrent.

now i changed the code to search in history first and then in queue.
so assigning will work for both locations now.

**Closed** 2024-03-07 12:57 UTC
